import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://www.facebook.com/flx/warn/?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fneighbors-curse%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExYkdKcFlUZDFoblBBYnZFM3NydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR6VyYAMGz5DtMkIQ-BvtZzPsn2mBHLchrAbcHtnRu9h3N6MgNouCeDrb7T-nA_aem_P0ruqAgY6GIwngmaVrQeUg&h=AUAAvIOR-VveGxSzYSpx9q79Sa4vLp103Ehd6ZX6rmGQmJtgjd4N8WCyMWfc5N4uv0GtfX3i4pjCHjqg-ao0kGqfIhruvkBFcesxGQw9UXanGtLrfT7MIPqKWeIDHZHu05bZx2XhAZby47YmcX1gk5b_tyNswFNqJ3NpTI3gvflcIh0i33XMiU6kxnqtOE-4cq8NOV1c-B-AQQZ1EZ8xYxyePRgkbRoksS_HOoT5QRAF8fZ6Z1rN7mdDQjFz_T9B');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.locator('//img[@loading="eager"]').first().click();
  await page.waitForTimeout(2000);
  await page.locator('//img[@loading="eager"]').first().click();
  await page.getByTestId('reader-next').click();
  await page.getByTestId('auth-email-input').click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test1', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fthirsty-dunes%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExYkdKcFlUZDFoblBBYnZFM3NydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR48cqxw5dbdq8N-JLVz8ywfl7x6L60vlj5o2X7j6UMLe8F4vW_pDQcCty9AoA_aem_QvKL05y7Q2bKGiLGiT3yIg&h=AUBtqB14DrX5y5mG1S5UX8NB_fpqSKilSY3eZSlKfeUFfbirmOsfXpK-5RnE1XCuHPVdHUll9chZZdRXhVk-flq-ifbnYeO3X-iSigXuUu6t1zs7cWdx44pWBNoCjUpqSLw7XADqBvQ&__tn__=H-R&c[0]=AUDwqt6NaW2nhREBObVb2arB3-CK99enipCauGQMJKfX8qmHZqEVgG7Ff6pXOUfwoqKOawqJ2v1HEcYiLjGTIlwZXBCmHbrOeRHsPrjEnroRXICHTMNTX7RUyRPxAag_SPFxsKtXqpC-JnPci_nx_cZ8s5z64Xm0DhLGonnwe0I');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.locator('//img[@loading="eager"]').first().click();
  await page.waitForTimeout(2000);
  await page.locator('//img[@loading="eager"]').first().click();
  await page.getByTestId('reader-next').click();
  await page.getByTestId('auth-email-input').click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test2', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.co%2Fcomics%2Fmy-sister-is-the-campus-queen%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExYkdKcFlUZDFoblBBYnZFM3NydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR682H5IfAQMmhTRfvc9PSssSlINe6-gFiCJ4AOUIiUJQgEkoRVu_UHAbtdahA_aem_nzIcP2t1Fcx-062Y4goJfg&h=AUCvs3rvvrl-azBe8JUC-sFRGnZcZj61U7NnaHyZyUsTDMRJy86M5RzSg0YUGsQc_wvwNZn_Qb1xII1EImM7GrLAy66FQ5h2eHsjP_JxxSXgS5zaOexiW5iKh83xGLM0Z37VuiGTZ5A&__tn__=H-R&c[0]=AUDKT5nB_w3dEmaandNx9JGnASZqeN8PldJgGQnrX92R1CJkpAXtRRcSM22qnPV9ZZHx4G6kbbmZPM4lTG9s_UrVarj1Qm4PrTXKiJwaU26r8-26K2ehRjq0ZE62CwTtp-9yo_PYc6tW_58ywdYuVQq8OXINRKOnEgay74WvNg');
  await page.getByRole('button', { name: 'Follow link' }).click();
  // await page.getByTestId('age-gate-confirm').click();
  // await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.locator('//img[@loading="eager"]').first().click();
  await page.waitForTimeout(2000);
  await page.locator('//img[@loading="eager"]').first().click();
  await page.getByTestId('reader-next').click();
  await page.getByTestId('auth-email-input').click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test3', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fpizza-boy-vs-milfs%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR75LA9wHKzY_Cl-fBhdT1FHDABr8YKm0k3e0Fw54rGgElz9gBwo9lOmvTHx1Q_aem_L0zrRXSyxIw5X6VcaJSxMA&h=AUDCCJQKjWAy9S9gYq4lXnvFokzoVdGxN82sdWzZ5B6WeZFeuicI8hsXLF5Y-1yfJPP4KOTrUH2NBQyc-dDsv_s70DzgHq2YUA_ZdX1_1mmysG4YqjMhF_91J2h-yJc0vxqIcEl8Xgc&__tn__=H-R&c[0]=AUBBKtbn41DrXWIIl-SSqUmRbFjbx0K5TF2XMdT0C5IdMF4HT2d6vO40fyvE0svZaahW2-2_ngjiuZaQ_oX3TPe1wgnRFCnMtHk1RQ0h75fzdfvn84f-jMnFrL8hF8vgtuoWTNBYTk9BipTPRWvf1s0yKDMMysijGZZ55F6wbYBT4y68F8Arrco');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test4', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fstepmoms-dirty-deal%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR5B4zLGx8dIh1xje59w8bOyaVir8gtC5gMTRAA3-m9NYVH87EERwejpK5JZ-g_aem_qp1Xgo5mR22TsHeXcrAbpQ&h=AUDIef80vEMWGlzGpNHMj_0z2Agq-xSFI9kmzcH-77aW1M6vBwuxwzOGK0C49h9-riGcwYEuBthYx9bSvx8pHNfIOXeMxqlJUDxIoDM9kHrJdj5XaaiCiYtsU63RQtXra4TeKTXbJIg&__tn__=H-R&c[0]=AUCrnbsPYQeoK_DDikLnCg9mKp9Q318uo6xjdd3MZAPSGQnFwZdaqeNN4EeQRkuNkhy7O5I0v_qH9Q378lWIDkEw_-9UNRf7gGX7HCvQzo58Q2hYgxhAqZRS8jGwAx4b0AY1-ZGZJU7nNTT3iTEFlJ_woRDv2n6XpF6WTyb58JiM6gBqUySyC80');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.locator('//img[@loading="eager"]').first().click();
  await page.waitForTimeout(2000);
  await page.locator('//img[@loading="eager"]').first().click();
  await page.getByTestId('reader-next').click();
  await page.getByTestId('auth-email-input').click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test5', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fsanum-lux-deep-restoration%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR6dZUPJnM4GefwgZdwBQSLP5izabDUDTulnDL-vL43b9isdLpVHRd4emedcwQ_aem_YVyvRfsBJ7B1X8ONy0ZG5g&h=AUA_eh6w_wYGzf7G8FELREGOVXUpZ_kIYp2vzEpTXQGND9Zu6cWN8vqG4abMmFbmJtLg3_F5hzzFEtUCg3dC0jbE2GU9DLv91ym8iVvSyByfNul4FT_Yrk912I5Xat1JirMX-HHprn0&__tn__=H-R&c[0]=AUDwUMlviQzkjBmC5OB2kk6eKfFOLqgA-KZ5CdtBK48XCdxqetkmCEWeI1XuPzH5f447Kq7FdCvXrPGD7rfBZq0j-40S4sR9aHM78zFFTaGatZxDPtCOZ5f5pUm6kvIIaNPeUvTmJhSGadEwObs1kZ5za_VeW2EAoClKpraUVM8');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

// test('test6', async ({ page }) => {
//   const randomPart = Math.random().toString(36).substring(2, 12);
//   const email = `testnewth${randomPart}@toonhub.com`;
//   await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fsis-begs-for-more%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR46XLfWA9pex4bKHHtxv-uOTmYYlC3FYUYUqFODGwxvfF2IrZJqCcwKtyXjQQ_aem_EVAUGU0WLDb1NnyyMnJeWg&h=AUDtSs7UCDiYbLEi_Zehe59qJWVc0zA3ZOI4xpyKbL5aTVy2LBLZ5W8lX5vWKkR57MEoNu2W5Sed2pfGK3SY1709lvjxjrmCtTLQmOPUwwtxAM0eQSvH7CpZNAsRsWZ7LDPuk400NOU&__tn__=H-R&c[0]=AUB5sdlHvSk4a8lpafHYvlfTbUInLNEVlImqPlU52D6NKQMo-0HoON6UWPi5xbhvKQdGaXO6VPTud9VuwBTqZdb_LMeqATWi0bFM0U7yfhyguxXXRoafv1hiI9kaZJ4s8KoNmadKuuoLJmqPHSytaIIe6rDajuSiL9SvlqrQgONINXcfdGr7w_Y');
//   await page.getByRole('button', { name: 'Follow link' }).click();
//   await page.getByTestId('age-gate-confirm').click();
//   await page.getByTestId('cookie-accept-all').click();
//   await page.getByRole('link', { name: 'Start reading' }).click();
//   await page.locator('//img[@loading="eager"]').first().click();
//   await page.waitForTimeout(2000);
//   await page.locator('//img[@loading="eager"]').first().click();
//   await page.getByTestId('reader-next').click();
//   await page.getByTestId('auth-email-input').click();
//   await page.getByTestId('auth-email-input').fill(email);
//   await page.getByTestId('auth-email-input').press('Tab');
//   await page.getByTestId('auth-continue-button').click();
//   await page.getByRole('textbox', { name: 'Your password' }).click();
//   await page.getByRole('textbox', { name: 'Your password' }).fill('1');
//   await page.waitForTimeout(2000);
//   await page.locator('//button[@data-testid="auth-create-account-button"]').click();
//   await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
//   await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
//   await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
//   await page.getByTestId('paywall-continue-button').click();
//   await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
//   await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
//   await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
//   await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
//   await page.close();
// });

test('test7', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Ftheir-perfect-plaything%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR7bPFz7qekqyErZeZVFDjd_hXW7p_EIxRpnILyL2UKX35KrGLV60VKQEu9v2Q_aem_ZphbadT8ox9nk3OSR80oEQ&h=AUDVga28PBdQNNu3-vkxWW-3hAWurpUGKkfBbmiFV644nCsLVBYCKXjQOHthbdnZ2hqAwPx0GVNPDvsNCS79e72D9RVEEavO1DJo3pW8_oYnIeHQV1mYIano0bIagzfwXdvq30t08rY&__tn__=H-R&c[0]=AUDDvmtNhoXPAhnDheNZ-n7aowQsbt3YbukWUBQH5lGAdoLfxfjEceqQYPQmhLMO3VZP5zbUO0I4dhM_HtsOFJ9621Wlc_M0xZW51Sr8yrQc6TLgBtUGtx6mC8PLVhl7b8bpm0Cmx5FUt8tnjxiV1TAVyMaues-ohWuzfrcIcA4jecXusu3wYO4');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.locator('//img[@loading="eager"]').first().click();
  await page.waitForTimeout(2000);
  await page.locator('//img[@loading="eager"]').first().click();
  await page.getByTestId('reader-next').click();
  await page.getByTestId('auth-email-input').click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test8', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fan-explosive-fourth%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR5eK0ga4rE5jqYaQgW-NfZQKu5Mg8JHIkp-Tgd4kcU__A8E8lWw-bZJjtPDew_aem_PvMBr-Hv_HxykI8vJgCo9Q&h=AUDd2kYqLgI_3GQtYA9RwAV9P1oW38KL12VwkmDlrxw56kqoL82uyiy9OoAuKb9ejXjjGLFrotrqOZ6k13v4hkcKd9KkYk9AL1tG6qQrgDRqSNO0QfJ1cdDBv0ZTFTfhhgF2pmhMHIg&__tn__=H-R&c[0]=AUAChziM6sO2qT_-C_WtpjViWD0XzfSe_i1y3UCpduRKZsiZyUVVFpUyhAmjIRhyPnOyEoqWEh9LyOEpY3QSlHFh9IXoYF1l_1dGOpHCkK6N6PlNEzYyyMOK4q_FBEnrOv5U8j13D1-V9HxC5lE71LV1HslcLjl3gOppjukxfN8');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.locator('//img[@loading="eager"]').first().click();
  await page.waitForTimeout(2000);
  await page.locator('//img[@loading="eager"]').first().click();
  await page.getByTestId('reader-next').click();
  await page.getByTestId('auth-email-input').click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});

test('test9', async ({ page }) => {
  const randomPart = Math.random().toString(36).substring(2, 12);
  const email = `testnewth${randomPart}@toonhub.com`;
  await page.goto('https://l.facebook.com/l.php?u=https%3A%2F%2Ftoon-hub.com%2Fcomics%2Fthey-all-want-me%2Fepisode-1%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTEAYnJpZBExUEVyWndOVmtwMmhhTHcwSHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR5ItWMBxbKmFbmRTFuvnynFHLWuTZYsZ2b1X26aJRQAjw8yqJQAYjCsziEiZA_aem_cwfvJL9kSFpEwvcinA5HAQ&h=AUBckyIxxFR4gYLUfQVHRlbvCTeRg38MiP4r8fvNS3WI0aAOPJdQJ4hKduQ4EOSAF7AAkHo-dgxIzG8iFAzaR0UDPhTK9tvfit41rN4L19XQflEabW-n7PECjUw4wFmhPHcMHN7Qwcc&__tn__=H-R&c[0]=AUDUuiewZx4-Un97qYW2XR-bYjt8V-WSlULyxyRuBNaLTE2kL5hDPbGxsYK91VrsvEUNPGuo8rP7dZqTTnVuLzEaCmxBbCOSzccenxkIYlrWkPNqnhkMjmsYjnBtxShyl5-JRunjVsDW2RCDXaw_osGaL3KVYjzNFz8AElxBG-v8SP_aJusHqf4');
  await page.getByRole('button', { name: 'Follow link' }).click();
  await page.getByTestId('age-gate-confirm').click();
  await page.getByTestId('cookie-accept-all').click();
  await page.getByRole('link', { name: 'Start reading' }).click();
  await page.getByTestId('auth-email-input').fill(email);
  await page.getByTestId('auth-email-input').press('Tab');
  await page.getByTestId('auth-continue-button').click();
  await page.getByRole('textbox', { name: 'Your password' }).click();
  await page.getByRole('textbox', { name: 'Your password' }).fill('1');
  await page.waitForTimeout(2000);
  await page.locator('//button[@data-testid="auth-create-account-button"]').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.locator('label:nth-child(3) > .SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').click();
  await page.locator('.SubscriptionVIPItem-module-scss-module__GFxAGq__subscription__card_content.SubscriptionVIPItem-module-scss-module__GFxAGq__sale > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__left > .SubscriptionVIPItem-module-scss-module__GFxAGq__product-card__circle').first().click();
  await page.getByTestId('paywall-continue-button').click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Credit Card Number' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'Expiration Date' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('iframe[name="solid-payment-form-iframe"]').contentFrame().getByTestId('submit-button').click();
  await page.close();
});